package br.com.pueyo.investimento.analise.modelo.constantes;

public enum IndiceBalancoEnum {
    INDICE_INDEPENDENCIA_FINANCEIRA, GRAU_ENDIVIDAMENTO, MARGEM_LIQUIDA, MARGEM_BRUTA, RENTABILIDADE_SOBRE_PATRIMONIO_LIQUIDO, LIQUIDEZ_SECA, LIQUIDEZ_IMEDIATA, LIQUIDEZ_CORRENTE, LUCRO_POR_ACAO, VALOR_PATRIMONIAL_POR_ACAO

}
