package br.com.pueyo.investimento.analise.modelo.constantes;

public enum ItemBalancoEnum {
    VENDAS_LIQUIDAS, LUCRO_LIQUIDO, PASSIVEL_EXIGIDO_LONGO_PRAZO, ATIVO_TOTAL, PATRIMONIO_LIQUIDO, LUCRO_BRUTO, ATIVO_CIRCULANTE, ESTOQUES, PASSIVO_CIRCULANTE, DISPONIBILIDADES, NUMERO_DE_ACOES

}
